In [2]:
import evaluate
my_metric = evaluate.load('bleu')
print(my_metric)
predictions = ["猫坐在垫子上"]
references = [["看！有只猫坐在垫子上", "垫子上有只猫"]]
results = my_metric.compute(predictions=predictions, references=references)
print("results:", results)

# 输出：
# results: {'bleu': 0.6431870218238024, 'precisions': [0.8333333333333334, 0.8, 0.75, 0.6666666666666666], 'brevity_penalty': 0.846481724890614, 'length_ratio': 0.8571428571428571, 'translation_length': 6, 'reference_length': 7}


Using the latest cached version of the module from /root/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--bleu/9e0985c1200e367cce45605ce0ecb5ede079894e0f24f54613fca08eeb8aff76 (last modified on Sat Apr 13 14:18:51 2024) since it couldn't be found locally at evaluate-metric--bleu, or remotely on the Hugging Face Hub.


EvaluationModule(name: "bleu", module_type: "metric", features: [{'predictions': Value(dtype='string', id='sequence'), 'references': Sequence(feature=Value(dtype='string', id='sequence'), length=-1, id='references')}, {'predictions': Value(dtype='string', id='sequence'), 'references': Value(dtype='string', id='sequence')}], usage: """
Computes BLEU score of translated segments against one or more references.
Args:
    predictions: list of translations to score.
    references: list of lists of or just a list of references for each translation.
    tokenizer : approach used for tokenizing `predictions` and `references`.
        The default tokenizer is `tokenizer_13a`, a minimal tokenization approach that is equivalent to `mteval-v13a`, used by WMT.
        This can be replaced by any function that takes a string as input and returns a list of tokens as output.
    max_order: Maximum n-gram order to use when computing BLEU score.
    smooth: Whether or not to apply Lin et al. 2004 smoot

In [3]:
import jieba
import evaluate
# my_metric = evaluate.load('bleu')
def wrap_str_in_lst(text):
    # 使用 jieba 进行精确分词
    segmented_text = jieba.cut(text, cut_all=False)
    # 直接返回分词结果的列表
    return list(segmented_text)

predictions = ["猫坐在垫子上"]
references = ["看！有只猫坐在垫子上"]

predictions = [wrap_str_in_lst(predictions[0])]
references = [[wrap_str_in_lst(references[0])]]
print(predictions)
print(references)
results = my_metric.compute(predictions=predictions, references=references)
print("results:", results)

/root/.conda/envs/medGPT/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.572 seconds.
Prefix dict has been built successfully.


[['猫', '坐在', '垫子', '上']]
[[['看', '！', '有', '只', '猫', '坐在', '垫子', '上']]]


NameError: name 'my_metric' is not defined

In [14]:
import evaluate

# 输入的预测和参考
predictions = ['猫', '坐在', '垫子', '上']
references = [['看', '！', '有', '只', '猫', '坐在', '垫子', '上']]

# 加载 BLEU 的评估器
# bleu = evaluate.load('bleu')

# 计算 BLEU score
results = my_metric.compute(predictions=[predictions], references=references)

print("BLEU score:", results['bleu'])


ValueError: Predictions and/or references don't match the expected format.
Expected format:
Feature option 0: {'predictions': Value(dtype='string', id='sequence'), 'references': Sequence(feature=Value(dtype='string', id='sequence'), length=-1, id='references')}
Feature option 1: {'predictions': Value(dtype='string', id='sequence'), 'references': Value(dtype='string', id='sequence')},
Input predictions: ['猫', '坐在', '垫子', '上'],
Input references: ['看', '！', '有', ..., '坐在', '垫子', '上']

In [17]:
import evaluate
import jieba

# 示例文本
candidate_text = "这是一个测试句子。"
reference_text = "这是一个测试的句子。"

# 使用 jieba 进行分词
candidate_tokens = ' '.join(list(jieba.cut(candidate_text))) 
reference_tokens = [' '.join(list(jieba.cut(reference_text)))]

# 加载 BLEU 的评估器
# bleu = evaluate.load('bleu')

# 计算 BLEU score
results = bleu.compute(predictions=[candidate_tokens], references=[reference_tokens])

print("BLEU score:", results['bleu'])


Using the latest cached version of the module from /root/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--bleu/9e0985c1200e367cce45605ce0ecb5ede079894e0f24f54613fca08eeb8aff76 (last modified on Sat Apr 13 14:18:51 2024) since it couldn't be found locally at evaluate-metric--bleu, or remotely on the Hugging Face Hub.


BLEU score: 0.0


In [19]:
from nltk.translate.bleu_score import corpus_bleu
from nltk.translate.bleu_score import SmoothingFunction

smooth = SmoothingFunction()

predictions = ["猫坐在垫子上"]
references = ["看！有只猫坐在垫子上"]

predicts = [wrap_str_in_lst(predictions[0])]
labels = [[wrap_str_in_lst(references[0])]]

# 注意这里的双重列表
# labels = [[['我', '是', '谁']]]
# predicts = [['我', '是', '谁']]

# 使用corpus_bleu计算语料库的BLEU分数
corpus_score_1 = corpus_bleu(labels, predicts, weights=(1, 0, 0, 0), smoothing_function=smooth.method1)
corpus_score_2 = corpus_bleu(labels, predicts, weights=(0.5, 0.5, 0, 0), smoothing_function=smooth.method1)
corpus_score_3 = corpus_bleu(labels, predicts, weights=(0.33, 0.33, 0.33, 0), smoothing_function=smooth.method1)
corpus_score_4 = corpus_bleu(labels, predicts, smoothing_function=smooth.method1)

print(corpus_score_1)
print(corpus_score_2)
print(corpus_score_3)
print(corpus_score_4)

0.36787944117144233
0.36787944117144233
0.36787944117144233
0.36787944117144233


In [33]:
from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import SmoothingFunction

smooth = SmoothingFunction()

predictions = ["猫坐在垫子上"]
references = ["看！有只猫坐在垫子上"]

predicts = wrap_str_in_lst(predictions[0])
labels = [wrap_str_in_lst(references[0])]
# 注意这里的双重列表
# labels = [[['我', '是', '谁']]]
# predicts = [['我', '是', '谁']]

# 使用corpus_bleu计算语料库的BLEU分数
sentence_score_1 = sentence_bleu(labels, predicts, weights=(1, 0, 0, 0), smoothing_function=smooth.method1)
sentence_score_2 = sentence_bleu(labels, predicts, weights=(0.5, 0.5, 0, 0), smoothing_function=smooth.method1)
sentence_score_3 = sentence_bleu(labels, predicts, weights=(0.33, 0.33, 0.33, 0), smoothing_function=smooth.method1)
sentence_score_4 = sentence_bleu(labels, predicts, smoothing_function=smooth.method1)

print(sentence_score_1)
print(sentence_score_2)
print(sentence_score_3)
print(sentence_score_4)

0.36787944117144233
0.36787944117144233
0.36787944117144233
0.36787944117144233


In [28]:
predictions = ["猫坐在垫子上"]
references = ["看！有只猫坐在垫子上"]
rouge = evaluate.load('rouge')
scores_rouge = rouge.compute(predictions=predictions, references=references)
print(scores_rouge)

{'rouge1': 0.0, 'rouge2': 0.0, 'rougeL': 0.0, 'rougeLsum': 0.0}


In [26]:
from rouge import Rouge
rouge_ch = Rouge()
rouge_ch.get_scores(' '.join(list('猫坐在垫子上')), ' '.join(list('看！有只猫坐在垫子上')))

[{'rouge-1': {'r': 0.6, 'p': 1.0, 'f': 0.7499999953125},
  'rouge-2': {'r': 0.5555555555555556, 'p': 1.0, 'f': 0.7142857096938776},
  'rouge-l': {'r': 0.6, 'p': 1.0, 'f': 0.7499999953125}}]

In [4]:
from rouge import Rouge
rouge_ch = Rouge()
predictions = ["猫坐在垫子上"]
references = ["看！有只猫坐在垫子上"]

predicts = wrap_str_in_lst(predictions[0])
labels = [wrap_str_in_lst(references[0])]
print(predicts,labels)
scores = rouge_ch.get_scores(' '.join(predicts), ' '.join(labels[0]))

['猫', '坐在', '垫子', '上'] [['看', '！', '有', '只', '猫', '坐在', '垫子', '上']]


In [6]:
scores[0]['rouge-1']['f']

0.6666666622222223

In [1]:
from bert_score import score
from transformers import AutoTokenizer, AutoModel

# 设置模型的本地路径
# model_path = "/data/cj_group/shuyu/model_zoo/bert-base-chinese"
model_path = '/data0/liushuyu/model_zoo/bert-base-chinese/'

# 加载分词器和模型
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModel.from_pretrained(model_path)

# 示例句子
cands = ["他的想法非常有创意。"]
refs = ["他的点子非常创新。"]

# 计算BERT-Score
P, R, F1 = score(cands, refs, model_type=model, tokenizer=tokenizer, verbose=True)

# 输出结果
print(f"Precisions: {P}")
print(f"Recalls: {R}")
print(f"F1 scores: {F1}")


TypeError: score() got an unexpected keyword argument 'tokenizer'

In [4]:
import json
with open('/data0/liushuyu/project/CMB_0523/data/psych/task1_100_checked.jsonl','r',encoding='utf-8') as f:
    for line in f.readlines():
        data = json.loads(line)
        print('-'*50)
        print(data['conversations'][2]['value'])

--------------------------------------------------
主诉：情绪不稳、疑心2月，加重20余日。 

 病例特点：1.病程标准：亚急性起病，病程2月。2.症状学标准：神清，接触差，态度蛮横，否认有病，情绪不稳，易激惹，行为冲动，无自知力。3.严重程度标准：社会功能受损。4.排除标准：暂无器质性疾病及精神活性物质所致精神障碍诊断依据。
--------------------------------------------------
主诉：情绪不稳定10天。 

 病例特点：1.病程标准：急性起病，连续病程10天2.症状学标准：情绪不稳定，易怒，冲动行为，睡眠障碍，思维联想增多。3.严重程度标准：社会功能受损明显。4.排除标准：排除脑器质性精神障碍，精神活性物质依赖和滥用所致精神障碍
--------------------------------------------------
主诉：间断情绪不稳，外走1年半，加重2个月。 

 病例特点：1.病程标准：急性起病，间断病程。2.症状学标准：情绪高涨，兴奋话多，易激惹，精力体力旺盛，挥霍钱财，整夜不眠与网友聊天，低级意向亢进，与家人争吵，冲动伤人。未引出幻觉及妄想等精神病性症状，夜间睡眠欠佳，饮食二便正常。意志活动减退，无自知力。3.严重程度标准：社会功能严重受损。4.排除标准：需排除器质性疾病所致精神障碍。
--------------------------------------------------
主诉：情绪不稳，打骂家人，想死3年余。 

 病例特点：1.病程标准：慢性起病，连续病程。2.症状学标准：患者意识清楚，定向力完整，接触不合作，言语活动较多，情绪急躁、易激惹，拒绝住院，打骂医护人员，行为鲁莽，表情愤怒，情感反应协调，无自知力。3.严重程度标准：社会功能明显受损。4.排除标准：除外器质性及精神活性物质所致的精神障碍。
--------------------------------------------------
主诉：间断情绪不稳1年，复犯1月兴奋话多 

 病例特点：1.病程标准：慢性起病，间断病程1年余2.症状学标准：患者意识清晰，定向力完整，接触被动，对答切题，询问下患者称晚上睡眠少，白天精力体力充沛，对自己评价高，认为自己能力强，称

In [17]:

import os
for task in [1,3,5]:
    # for model in ['glm','kimi','ernie','sparkle','baichuan','doubao','yi']:
    for model in ['yi']:
        ans_path = '/data/cj_group/shuyu/CMB_0523/result/API/task{}_{}.json'.format(task,model)
        dir_out = './result/PsychClinical/{}_api/task{}'.format(model,task)
        os.system('python /data/cj_group/shuyu/CMB_0523/src/calc_metrics.py --ans_path {} --dir_out {}'.format(ans_path,dir_out))

0it [00:00, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.802 seconds.
Prefix dict has been built successfully.
10it [00:02,  3.62it/s]
/home/cj_group/miniconda3/envs/medGPT/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/cj_group/miniconda3/envs/medGPT/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


accuracy: nan


0it [00:00, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.770 seconds.
Prefix dict has been built successfully.
10it [00:03,  3.31it/s]
/home/cj_group/miniconda3/envs/medGPT/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/cj_group/miniconda3/envs/medGPT/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


accuracy: nan


0it [00:00, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.789 seconds.
Prefix dict has been built successfully.
10it [00:02,  3.56it/s]
/home/cj_group/miniconda3/envs/medGPT/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/cj_group/miniconda3/envs/medGPT/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


accuracy: nan


In [18]:
import tqdm
import numpy as np 
import os
import json 

## 完整性
def compute_integrity(ans):
    cnt = 0
    if '病程标准' in ans: cnt += 1
    if '症状学标准' in ans: cnt += 1
    if '严重程度标准' in ans: cnt += 1
    if '排除标准' in ans: cnt += 1
    
    return cnt/4

## 准确性
import re
def find_time(text):
    # 使用正则表达式匹配时间描述
    time_patterns = [
        r'\d+年',
        r'\d+月',
        r'\d+天',
        # r'\d+余',
        r'\d+余日',
        r'\d+余月',
        r'\d+余年'
    ]

    times_found = []
    for pattern in time_patterns:
        times_found.extend(re.findall(pattern, text))

    # 去重并排序结果
    unique_times = sorted(set(times_found))
    return unique_times

def find_des(text):
    # 使用正则表达式匹配时间描述
    des_patterns = [
        r'慢性',
        r'急性',
        r'持续',
        r'连续',
        r'间断',
        r'亚急性',
        r'反复',
        r'波动',
    ]

    des_found = []
    for pattern in des_patterns:
        des_found.extend(re.findall(pattern, text))

    # 去重并排序结果
    unique_times = sorted(set(des_found))
    if '急性' in unique_times and '亚急性' in unique_times:
        unique_times = [a for a in unique_times if a != '急性']
    
    return unique_times

import re
def find_icd(text):
    # text = "患者的主要诊断是 F30.901，需要进行进一步的治疗。"
    icd_dict = {}
    with open('/data/cj_group/shuyu/CMB_0523/data/psych/icd-10.jsonl','r',encoding='utf-8') as f:
        for line in f.readlines():
            data = json.loads(line)
            icd_dict[data["ICD-10 Name"]] = data['ICD-10 Code']
    icd10_codes = re.findall(r'\bF\d+\.\d+\b', text)
    if len(icd10_codes) < 1:
        for name in icd_dict.keys():
            if name in text:
                return icd_dict[name]
        print(text)
        return ''
    return icd10_codes[0]  # 输出: ['F30.901']

def acc_task1(out,tgt):
    out_zs = out.split('主诉')[1].split('病程标准')[0].split('病例特点')[0].replace('：','').replace(':','').replace('\n','')
    tgt_zs = tgt.split('主诉：')[1].split('病例特点')[0].replace('\n','')
    
    hit = 0
    tgt_num = 0
    
    times_zs = find_time(tgt_zs)
    tgt_num += len(times_zs)
    for t in times_zs:
        if t in out_zs:
            hit += 1
            
    out_bc = out.split('病程标准')[1].split('症状学标准')[0].replace('：','').replace(':','').replace('\n','').replace('*','')
    tgt_bc = tgt.split('病程标准：')[1].split('2')[0].replace('\n','')
    key_bc =  find_time(tgt_bc) + find_des(tgt_bc)
    tgt_num += len(key_bc)
    for k in key_bc:
        if k in out_bc:
            hit += 1
    
    out_yz = out.split('严重程度标准')[1].split('排除标准')[0].replace('：','').replace(':','').replace('\n','').replace('*','')
    tgt_yz = tgt.split('严重程度标准：')[1].split('4')[0].replace('\n','')
    opt = ['严重','明显','轻微']
    key_yz =  [o for o in opt if o in tgt_yz]
    tgt_num += len(key_yz)
    for k in key_yz:
        if k in out_yz:
            hit += 1

    acc = hit / tgt_num
    return acc

def acc_task2(out,tgt):
    out_icd = find_icd(out)
    icd_dict = {}
    with open('/data/cj_group/shuyu/CMB_0523/data/psych/icd-10.jsonl','r',encoding='utf-8') as f:
        for line in f.readlines():
            data = json.loads(line)
            icd_dict[data["ICD-10 Name"]] = data['ICD-10 Code']
    tgt_icd = icd_dict[tgt.split('主要诊断：')[1].replace(' ','')]
    
    acc = 0
    if out_icd[:5] == tgt_icd[:5]:
        acc = 0.5
    if out_icd == tgt_icd:
        acc = 1
    return acc

def acc_task3(out,tgt):
    try:
        out = out.split('主要诊断')[-1].split('鉴别诊断')[0]
    except:
        out = out.split('鉴别诊断')[0]
        # print(out)
    if tgt in out:
        acc = 1
    else:
        acc = 0
    return acc 



from fuzzywuzzy import fuzz

def fuzzy_match(str1, str2):
    """
    使用 Fuzzywuzzy 库进行模糊匹配，返回两个字符串之间的相似度百分比。
    """
    ratio = fuzz.ratio(str1, str2)
    if ratio > 0.5:
        return True
    else:
        return False
    
def fuzzy_match_list(str1, tgt_list):
    """
    使用 Fuzzywuzzy 库进行模糊匹配，返回两个字符串之间的相似度百分比。
    """
    flag = False
    for str2 in tgt_list:
        if fuzzy_match(str1,str2):
            flag = True
            break
    return flag

def hit_task4(out,tgt):
    out = out.replace('，',',').replace(' ','')
    tgt = tgt.replace('，',',').replace(' ','')
    try:
        out_list = out.split('推荐药物：')[1].split('分析')[0].split(',')
    except:
        out_list = out.split('分析')[0].split(',')
    tgt_list = tgt.split(',')
    
    ## 最后没用fuzzy match而是在prompt中加了约束，因为奥氮平、米氮平等药物名称的相似性很高
    # o_in_t = [d for d in out_list if fuzzy_match_list(d,tgt_list)]
    # t_in_o = [d for d in tgt_list if fuzzy_match_list(d,out_list)]
    # acc = 0
    # if fuzzy_match(out_list[0],tgt_list[0]):
    
    o_in_t = [d for d in out_list if d in tgt_list]
    t_in_o = [d for d in tgt_list if d in out_list]
    acc = 0
    if out_list[0]==tgt_list[0]:
        acc = 1
    recall = len(t_in_o) / len(tgt_list)
    precision = len(o_in_t) / len(out_list)
    
    return acc,precision,recall
        

for task in [1,2,3,4]:
# for task in [2]:
    print('-'*100)
    print('task',task)
    for model in ['glm','kimi','ernie','sparkle','baichuan','qwen','doubao','yi']:
    # for model in ['baichuan']:
        ans_path = '/data/cj_group/shuyu/CMB_0523/result/API/task{}_{}.json'.format(task,model)
        # load data
        lst_tgt = []
        lst_out = []
        lst_idx = []
        option_qa = [[],[]]
        with open(ans_path, "r", encoding="utf-8") as f:
            answers = json.load(f)
        idx = 0
        for ans in answers:
            if 'question_type' not in ans.keys():
                ans['question_type'] = 'clinical'
            if '选择题' in ans['question_type']:
                option_qa[0].append(ans['answer'])
                option_qa[1].append(ans['model_answer'])
                idx += 1
            else:
                if ans['question_type'] == 'clinical':
                    if ans['conversations'][1]['from']=='gpt':
                        lst_tgt.append(ans['conversations'][1]['value'])
                    else:
                        lst_tgt.append(ans['conversations'][2]['value'])
                else:
                    lst_tgt.append(ans['answer'])
                # lst_out.append(ans['model_answer'])
                lst_out.append(ans['answer_0'])
                
                lst_idx.append(idx)
                idx += 1

        # compute scores of each sample across entire dataset
        scores_all = {}
        # for tgt, out, idx in tqdm.tqdm(zip(lst_tgt, lst_out, lst_idx)):
        for tgt, out, idx in zip(lst_tgt, lst_out, lst_idx):

            if out == 'API调用失败':
                continue
            # get sub-dict containing scores for each metric
            # task1
            if 'task1' in ans_path:
                scores = [compute_integrity(out),acc_task1(out,tgt)]
            
            # task2
            if 'task2' in ans_path:
                scores = acc_task2(out,tgt)
            
            # task3
            if 'task3' in ans_path:
                tgt = re.findall(r'\[(.*?)\]', answers[idx]['conversations'][0]['value'])[0]
                scores = acc_task3(out,tgt)
            
            # task4
            if 'task4' in ans_path:
                scores = hit_task4(out,tgt)

            # append to master dict, dataset object
            scores_all[idx] = scores

        print(np.mean(np.array(list(scores_all.values())),0))

----------------------------------------------------------------------------------------------------
task 1
[1.         0.36296296]
[1.         0.31666667]
[1.         0.40740741]
[1.         0.26666667]
[1.         0.43703704]
[1.    0.405]
[1.         0.18666667]
[1.         0.18666667]
----------------------------------------------------------------------------------------------------
task 2
0.3
0.125
0.5
0.5555555555555556
0.0
0.4
0.4
0.3
----------------------------------------------------------------------------------------------------
task 3
0.8888888888888888
0.8
1.0
0.5
0.8
0.5
0.5
0.5
----------------------------------------------------------------------------------------------------
task 4
[0.         0.16666667 0.24074074]
[0.11111111 0.21296296 0.25925926]
[0.3   0.275 0.4  ]
[0.42857143 0.39285714 0.39285714]
[0.4        0.23333333 0.3       ]
[0.3        0.14166667 0.23333333]
[0.1        0.15833333 0.23333333]
[0.1        0.15833333 0.23333333]


In [18]:
find_icd("患者的主要诊断是 F30.901，需要进行进一步的治疗。")


'F30.901'

In [29]:
# task3 prompt 的格式转换
with open('/data0/liushuyu/project/CMB_0523/data/psych/task3_1.jsonl', 'w', encoding='utf-8') as outfile:
    with open('/data0/liushuyu/project/CMB_0523/data/psych/task3.jsonl','r',encoding='utf-8') as f:
        for line in f.readlines():
            data = json.loads(line)
            prompt = data['conversations'][1]['value'].split('\n')[0].replace('属于','属于[').replace('还是',']还是[').replace('。',']。')
            data['conversations'][1]['value'] = '\n'.join([prompt]+data['conversations'][1]['value'].split('\n')[1:])
            json_object_modified = json.dumps(data,ensure_ascii=False)
            outfile.write(json_object_modified + '\n')

In [19]:
# task5 prompt 的格式转换(多轮)
import re
with open('/data/cj_group/shuyu/CMB_0523/data/psych/task5_1.jsonl', 'w', encoding='utf-8') as outfile:
    with open('/data/cj_group/shuyu/CMB_0523/data/psych/task5.jsonl','r',encoding='utf-8') as f:
        for line in f.readlines():
            data = json.loads(line)
            prompt = re.split('问题\d*：|答案\d*：',data['conversations'][1]['value'])[1:]
            # prompt = data['conversations'][1]['value'].split('答案')
            
            for i in range(3):
                if i == 0:
                    data['conversations'][0]['value'] += '问题1：' + prompt[i]
                    data['conversations'][1]['value'] = prompt[i+1]
                    
                else:
                    data['conversations'].append({'from':'human','value':'问题{}：'.format(i+1) + prompt[2*i]})
                    data['conversations'].append({'from':'gpt','value': prompt[2*i+1]})
                    
            json_object_modified = json.dumps(data,ensure_ascii=False)
            outfile.write(json_object_modified + '\n')

In [4]:
# task5 prompt 的格式转换(单轮)
import re
import json
with open('../data/psych/task5_1.jsonl', 'w', encoding='utf-8') as outfile:
    with open('../data/psych/task5.jsonl','r',encoding='utf-8') as f:
        for line in f.readlines():
            data = json.loads(line)
            prompt = re.split('问题\d*：|答案\d*：',data['conversations'][1]['value'])[1:]
            # prompt = data['conversations'][1]['value'].split('答案')
            
            for i in range(3):
                if i == 0:
                    data['conversations'][0]['value'] += '\n问题1：' + prompt[i]
                    data['conversations'][1]['value'] = '答案1：' + prompt[i+1]
                    
                else:
                    data['conversations'][0]['value'] += '\n问题{}：'.format(i+1) + prompt[2*i]
                    data['conversations'][1]['value'] += '\n答案{}：'.format(i+1) + prompt[2*i+1]
                    
            json_object_modified = json.dumps(data,ensure_ascii=False)
            outfile.write(json_object_modified + '\n')

In [4]:
from fuzzywuzzy import fuzz

def fuzzy_match(str1, str2):
    """
    使用 Fuzzywuzzy 库进行模糊匹配，返回两个字符串之间的相似度百分比。
    """
    ratio = fuzz.ratio(str1, str2)
    return ratio

# 示例用法
str1 = "奥氮平"
str2 = "氯氮平"
similarity = fuzzy_match(str1, str2)
print(f"相似度为: {similarity}%")


相似度为: 67%


In [10]:
# task3 prompt 的格式转换
import json
import re
import numpy as np
main = []
diff = []
answer_dict = {}
with open(r"E:\project\LM\benchmark_data\benchmark_0720\task3_w_hint_formatted.jsonl", 'w', encoding='utf-8') as outfile:
    with open(r"E:\project\LM\benchmark_data\benchmark_0720\task3_w_hint.jsonl",'r',encoding='utf-8') as f:
        for id,line in enumerate(f.readlines()):
            data = json.loads(line)
            prompt = data['conversations'][1]['value'].split('\n')[0].replace('请针对','请针对[').replace('和',']和[').replace('进行',']进行')
            data['conversations'][1]['value'] = '\n'.join([prompt]+data['conversations'][1]['value'].split('\n')[1:])
            answer = re.findall(r'\[(.*?)\]', prompt)
            data['answer'] = {'main':answer[0],'diff':answer[1:]}
            answer_dict['clinical-{}'.format(id)] = {'main':answer[0],'diff':answer[1:]}
            main.append(answer[0])
            diff.extend(answer[1:])
            json_object_modified = json.dumps(data,ensure_ascii=False)
            outfile.write(json_object_modified + '\n')


np.save('../data/psych/task3_ans.npy',answer_dict)
name,cnt = np.unique(main,return_counts=True)
for n,c in zip(name,cnt):
    print(n,c)
print('-'*50)
name,cnt = np.unique(diff,return_counts=True)
for n,c in zip(name,cnt):
    print(n,c)

print('-'*50)
name,cnt = np.unique(main+diff,return_counts=True)
for n,c in zip(name,cnt):
    print(n,c)

双相情感障碍 18
复发性抑郁障碍 19
抑郁发作 19
精神分裂症 23
躁狂发作 21
--------------------------------------------------
人格障碍 1
双相情感障碍 30
器质性精神障碍 2
复发性抑郁障碍 1
妄想性障碍 2
广泛性焦虑障碍 3
强迫性障碍 1
心境障碍 2
急性而短暂的精神病性障碍 3
急性而短暂的精神障碍 1
抑郁发作 9
抑郁障碍 5
焦虑障碍 5
环性心境 1
精神分裂症 22
精神障碍 4
脑器质性精神病 1
躁狂发作 4
躯体症状障碍 1
酒精所致的精神行为障碍 1
酒精所致精神及行为障碍 1
--------------------------------------------------
人格障碍 1
双相情感障碍 48
器质性精神障碍 2
复发性抑郁障碍 20
妄想性障碍 2
广泛性焦虑障碍 3
强迫性障碍 1
心境障碍 2
急性而短暂的精神病性障碍 3
急性而短暂的精神障碍 1
抑郁发作 28
抑郁障碍 5
焦虑障碍 5
环性心境 1
精神分裂症 45
精神障碍 4
脑器质性精神病 1
躁狂发作 25
躯体症状障碍 1
酒精所致的精神行为障碍 1
酒精所致精神及行为障碍 1
